import { GEMINI_MODEL, AI_ENDPOINTS, getGeminiApiKey } from '@/config/ai';

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export class GeminiError extends Error {
  statusCode?: number;
  constructor(message: string, statusCode?: number) {
    super(message);
    this.name = 'GeminiError';
    this.statusCode = statusCode;
  }
}

/**
 * Calls Google Gemini API using the centralized configuration.
 *
 * @param userPrompt The user's query with any minimized health context.
 * @param systemInstruction System personality and behavioral rules.
 * @returns The text response generated by Gemini.
 * @throws GeminiError if the call fails or no API key is configured.
 */
export async function callGemini(
  userPrompt: string,
  systemInstruction?: string
): Promise<string> {
  const apiKey = getGeminiApiKey();

  if (!apiKey || apiKey === 'YOUR_GEMINI_API_KEY') {
    throw new GeminiError('Gemini API key is not configured.', 401);
  }

  const endpoint = AI_ENDPOINTS.gemini(GEMINI_MODEL, apiKey);

  const payload: Record<string, unknown> = {
    contents: [
      {
        role: 'user',
        parts: [{ text: userPrompt }],
      },
    ],
    generationConfig: {
      temperature: 0.4,
      maxOutputTokens: 800,
    },
  };

  if (systemInstruction) {
    payload.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    const errorMsg =
      (data as { error?: { message?: string } })?.error?.message ||
      `HTTP ${response.status} from Gemini`;
    throw new GeminiError(errorMsg, response.status);
  }

  const candidates = (data as {
    candidates?: { content?: { parts?: { text?: string }[] } }[];
  })?.candidates;

  const replyText = candidates?.[0]?.content?.parts?.[0]?.text?.trim();

  if (!replyText) {
    throw new GeminiError('Empty response candidate returned by Gemini.');
  }

  return replyText;
}
