import { GROQ_MODEL, AI_ENDPOINTS, getGroqApiKey } from '@/config/ai';

export class GroqError extends Error {
  statusCode?: number;
  constructor(message: string, statusCode?: number) {
    super(message);
    this.name = 'GroqError';
    this.statusCode = statusCode;
  }
}

/**
 * Calls Groq chat completions API using the centralized configuration.
 *
 * @param userPrompt The user's query with any minimized health context.
 * @param systemInstruction System personality and behavioral rules.
 * @returns The text response generated by Groq.
 * @throws GroqError if the call fails or no API key is configured.
 */
export async function callGroq(
  userPrompt: string,
  systemInstruction?: string
): Promise<string> {
  const apiKey = getGroqApiKey();

  if (!apiKey || apiKey === 'YOUR_GROQ_API_KEY') {
    throw new GroqError('Groq API key is not configured.', 401);
  }

  const messages: { role: 'system' | 'user'; content: string }[] = [];

  if (systemInstruction) {
    messages.push({
      role: 'system',
      content: systemInstruction,
    });
  }

  messages.push({
    role: 'user',
    content: userPrompt,
  });

  const response = await fetch(AI_ENDPOINTS.groqChat, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: GROQ_MODEL,
      messages,
      temperature: 0.4,
      max_tokens: 800,
    }),
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    const errorMsg =
      (data as { error?: { message?: string } })?.error?.message ||
      `HTTP ${response.status} from Groq`;
    throw new GroqError(errorMsg, response.status);
  }

  const replyText = (data as {
    choices?: { message?: { content?: string } }[];
  })?.choices?.[0]?.message?.content?.trim();

  if (!replyText) {
    throw new GroqError('Empty response content returned by Groq.');
  }

  return replyText;
}
